### ISSUE TITLE
cmake: command not found

### ISSUE THREAD

**Issue by EsTaNG9** [danielkrupinski/csgo-champion#1]
./build: line 3: cmake: command not found

I'm getting this error on this command: "cmake . || exit 1".
I don't have an idea why.

OS: Linux Mint

**Comment by danielkrupinski** [comment]
You need to install cmake.

**Comment by EsTaNG9** [comment]
Thank you for the help, I think I uninstalled it while trying to install it.
But anyways now when I try to compile it is giving me a couple of errors. I would be happy if you could help me with that and thank you for your time by the way.

### ./build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/estang/Downloads/csgo-champion-master
[ 11%] Building CXX object CMakeFiles/champion.dir/src/keylistener.cpp.o
[ 22%] Building CXX object CMakeFiles/champion.dir/src/musickit_changer.cpp.o
[ 33%] Building CXX object CMakeFiles/champion.dir/src/main.cpp.o
[ 44%] Building CXX object CMakeFiles/champion.dir/src/cheat.cpp.o
In file included from /home/estang/Downloads/csgo-champion-master/src/keylistener.h:12:0,
                 from /home/estang/Downloads/csgo-champion-master/src/keylistener.cpp:1:
/home/estang/Downloads/csgo-champion-master/src/remote.h:90:22: error: enclosing class of constexpr non-static member function ‘pid_t remote::Handle::GetPid()’ is not a literal type
      constexpr pid_t GetPid(){ return pid; }
                      ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note: ‘remote::Handle’ is not literal because:
  class Handle {
        ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note:   ‘remote::Handle’ has a non-trivial destructor
/home/estang/Downloads/csgo-champion-master/src/remote.h:94:21: error: enclosing class of constexpr non-static member function ‘bool remote::Handle::IsValid()’ is not a literal type
      constexpr bool IsValid();
                     ^
In file included from /home/estang/Downloads/csgo-champion-master/src/cheat.h:16:0,
                 from /home/estang/Downloads/csgo-champion-master/src/musickit_changer.h:4,
                 from /home/estang/Downloads/csgo-champion-master/src/musickit_changer.cpp:1:
/home/estang/Downloads/csgo-champion-master/src/remote.h:90:22: error: enclosing class of constexpr non-static member function ‘pid_t remote::Handle::GetPid()’ is not a literal type
      constexpr pid_t GetPid(){ return pid; }
                      ^
In file included from /home/estang/Downloads/csgo-champion-master/src/keylistener.h:12:0,
                 from /home/estang/Downloads/csgo-champion-master/src/main.cpp:11:
/home/estang/Downloads/csgo-champion-master/src/remote.h:90:22: error: enclosing class of constexpr non-static member function ‘pid_t remote::Handle::GetPid()’ is not a literal type
      constexpr pid_t GetPid(){ return pid; }
                      ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note: ‘remote::Handle’ is not literal because:
  class Handle {
        ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note:   ‘remote::Handle’ has a non-trivial destructor
/home/estang/Downloads/csgo-champion-master/src/remote.h:94:21: error: enclosing class of constexpr non-static member function ‘bool remote::Handle::IsValid()’ is not a literal type
      constexpr bool IsValid();
                     ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note: ‘remote::Handle’ is not literal because:
  class Handle {
        ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note:   ‘remote::Handle’ has a non-trivial destructor
/home/estang/Downloads/csgo-champion-master/src/remote.h:94:21: error: enclosing class of constexpr non-static member function ‘bool remote::Handle::IsValid()’ is not a literal type
      constexpr bool IsValid();
                     ^
In file included from /home/estang/Downloads/csgo-champion-master/src/cheat.h:16:0,
                 from /home/estang/Downloads/csgo-champion-master/src/cheat.cpp:1:
/home/estang/Downloads/csgo-champion-master/src/remote.h:90:22: error: enclosing class of constexpr non-static member function ‘pid_t remote::Handle::GetPid()’ is not a literal type
      constexpr pid_t GetPid(){ return pid; }
                      ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note: ‘remote::Handle’ is not literal because:
  class Handle {
        ^
/home/estang/Downloads/csgo-champion-master/src/remote.h:50:8: note:   ‘remote::Handle’ has a non-trivial destructor
/home/estang/Downloads/csgo-champion-master/src/remote.h:94:21: error: enclosing class of constexpr non-static member function ‘bool remote::Handle::IsValid()’ is not a literal type
      constexpr bool IsValid();
                     ^
CMakeFiles/champion.dir/build.make:182: recipe for target 'CMakeFiles/champion.dir/src/musickit_changer.cpp.o' failed
make[2]: *** [CMakeFiles/champion.dir/src/musickit_changer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/champion.dir/build.make:110: recipe for target 'CMakeFiles/champion.dir/src/keylistener.cpp.o' failed
make[2]: *** [CMakeFiles/champion.dir/src/keylistener.cpp.o] Error 1
CMakeFiles/champion.dir/build.make:158: recipe for target 'CMakeFiles/champion.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/champion.dir/src/main.cpp.o] Error 1
CMakeFiles/champion.dir/build.make:62: recipe for target 'CMakeFiles/champion.dir/src/cheat.cpp.o' failed
make[2]: *** [CMakeFiles/champion.dir/src/cheat.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/champion.dir/all' failed
make[1]: *** [CMakeFiles/champion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by danielkrupinski** [comment]
Your compiler is outdated.

**Comment by EsTaNG9** [comment]
The compiler you mean gcc right?

And I cant thank you enough for your patience with me

**Comment by danielkrupinski** [comment]
Yes, I mean gcc. You should update it to version 7.2 or 7.3. To check current version you can type in terminal
```
g++ --version
```

**Comment by EsTaNG9** [comment]
I'm not being able to to update gcc but thank you for your time anyway.
--//--
Actually I was able to compile it, thank you for your time.
